import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'

export default function Home() {
  return (
    <div>

      <header className={styles.header} >

        <div className={styles.exercise}>
          <Image className={styles.logo}
            src="melysa_logo.svg"
            width={100}
            height={100} />
          Next.js Expo Line Map Exercise</div>
      </header>

      <div className={styles.container}>
        <Head>
          <title>Expo Line Map - Melysa Nguyen</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/melysa_icon.svg" />
        </Head>
        <main className={styles.main}>
          <Map />
        </main>

      </div>

      <footer className={styles.footer}>
        <a
          href="https://github.com/melysan"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Melysa Nguyen
          <span className={styles.logo}>
            <Image src="/melysa_icon.svg" alt="Melysa Nguyen Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}
